// Module scaffold is generated by emscripten.
// async function createEphone(moduleArg = {}) {
//   var Module = moduleArg;
//   var ENVIRONMENT_IS_WEB, ENVIRONMENT_IS_WORKER, ENVIRONMENT_IS_NODE = ...

let _voicePacks;
if (Array.isArray(Module)) {
  Module = {};
  _voicePacks = moduleArg;
} else if (typeof Module === 'function') {
  Module = {};
  _voicePacks = [moduleArg];
} else if (Array.isArray(Module?.languages)) {
  _voicePacks = Module.languages;
} else if (typeof Module?.languages === 'function') {
  _voicePacks = [Module.languages];
} else {
  if (!Module || typeof Module !== 'object') Module = {};
  _voicePacks = [_defaultLang];
}

Module._voices = new Map();
Module._addLangMeta = (meta) => {
  for (const [name, path, desc] of meta.voices) {
    Module._voices.set(name.toLowerCase(), [name, meta.name, path, desc]);
  }
};

if (typeof Module.preRun === 'function') {
  Module.preRun = [Module.preRun];
} else if (!Array.isArray(Module.preRun)) {
  Module.preRun = [];
}

for (const vp of _voicePacks) {
  if (typeof vp === 'function') await vp(Module);
}
