name: Build Multiple

on:
  push:
    branches: ['**']
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 cmake
          git clone --depth 1 https://github.com/emscripten-core/emsdk.git /opt/emsdk
          cd /opt/emsdk
          ./emsdk install latest
          ./emsdk activate latest

      - name: Run Build
        shell: bash
        run: |
          source /opt/emsdk/emsdk_env.sh
          emscripten/build-multiple.sh
          cd build/dist && npm pack

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ephone-dist
          path: build/dist/
